# Generated by Django 5.2 on 2025-09-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='text',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject_of_text',
            new_name='subject_of_message',
        ),
    ]
