# Generated by Django 5.2 on 2025-09-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_fullname_contact_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject_of_message',
            field=models.CharField(choices=[('complains', 'شكوى'), ('criticism', 'نقد بناء'), ('other', 'شيء أخر')], default='complains', max_length=50),
        ),
    ]
