# Generated by Django 5.1.7 on 2025-05-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeuser',
            name='password2',
        ),
    ]
