# Generated by Django 5.2 on 2025-05-03 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinguser',
            old_name='user',
            new_name='passenger',
        ),
        migrations.RemoveField(
            model_name='bookinguser',
            name='seat_count',
        ),
        migrations.AddField(
            model_name='bookinguser',
            name='booking_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bookinguser',
            name='seat_number',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinguser',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
