# Generated by Django 5.1.7 on 2025-05-07 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_bookinguser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinguser',
            name='seats_numbers',
        ),
        migrations.AlterField(
            model_name='bookinguser',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 7, 22, 36, 4, 605796)),
        ),
    ]
