# Generated by Django 5.2 on 2025-05-08 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_bookinguser_seats_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinguser',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 22, 54, 21, 464152)),
        ),
    ]
