# Generated by Django 5.1.7 on 2025-05-10 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_bookinguser_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinguser',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
