# Generated by Django 5.1.7 on 2025-05-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='arrival_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.DateField(),
        ),
    ]
