# Generated by Django 5.1.7 on 2025-05-07 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_arrival_time_alter_trip_departure_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='arrival_time',
            new_name='departure_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='departure_time',
        ),
        migrations.AddField(
            model_name='trip',
            name='time_of_travel',
            field=models.TimeField(default=datetime.time),
        ),
    ]
