# Generated by Django 5.1.7 on 2025-05-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_rename_arrival_time_trip_departure_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='time_of_travel',
            field=models.TimeField(),
        ),
    ]
