# Generated by Django 5.1.7 on 2025-05-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trip_time_of_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='total_seats',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='trip',
            name='available_seats',
            field=models.IntegerField(default=models.IntegerField(default=40)),
        ),
    ]
