# Generated by Django 5.1.7 on 2025-05-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_total_seats_alter_trip_available_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='available_seats',
            field=models.IntegerField(default=models.IntegerField()),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_seats',
            field=models.IntegerField(),
        ),
    ]
