# Generated by Django 5.2 on 2025-05-08 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_trip_available_seats_alter_trip_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
