# Generated by Django 5.1.7 on 2025-05-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_alter_trip_departure_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='time_of_travel',
        ),
    ]
