# Generated by Django 5.2 on 2025-05-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
    ]
