# Generated by Django 5.2 on 2025-09-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_remove_typeuser_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
