# Generated by Django 5.2 on 2025-05-03 09:04

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_populate_phone_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeuser',
            name='password2',
            field=models.CharField(default='12345678qwertyui', max_length=300),
        ),
        migrations.AlterField(
            model_name='typeuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0000000', max_length=128, region=None),
        ),
    ]
