# Generated by Django 5.2 on 2025-05-03 09:04

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0003_typeuser_password2_alter_typeuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeuser',
            name='password2',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='typeuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
