# Generated by Django 5.2 on 2025-09-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0003_alter_typeuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeuser',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
