# Generated by Django 5.1.7 on 2025-05-07 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_user_bookinguser_passenger_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinguser',
            options={'ordering': ['-booking_date'], 'verbose_name_plural': 'Bookings'},
        ),
        migrations.RenameField(
            model_name='bookinguser',
            old_name='passenger',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='bookinguser',
            name='booking_time',
        ),
        migrations.RemoveField(
            model_name='bookinguser',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='bookinguser',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 7, 21, 38, 0, 987152)),
        ),
        migrations.AddField(
            model_name='bookinguser',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinguser',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookinguser',
            name='number_of_seats',
            field=models.PositiveIntegerField(default='3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinguser',
            name='seats_numbers',
            field=models.JSONField(default=list),
        ),
    ]
