# Generated by Django 5.1.7 on 2025-05-09 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_bookinguser_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinguser',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
