# Generated by Django 5.2.1 on 2025-05-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_remove_trip_time_of_travel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='available_seats',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_seats',
            field=models.PositiveIntegerField(),
        ),
    ]
