# Generated by Django 5.2 on 2025-09-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_alter_trip_available_seats_alter_trip_departure_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
