# Generated by Django 5.2 on 2025-05-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
